name: Build and Package App

on:
  push:
    branches: [ main ] # Adjust branch as needed

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build app
        run: dotnet build --configuration Release

      - name: Publish app
        run: dotnet publish -c Release -o ./publish

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-app # Change to your app name
          path: ./publish
