name: CI/CD for CRUD App

on:
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0' 

      - name: Restore dependencies
        run: dotnet restore

      - name: Build app
        run: dotnet build --configuration Release

      - name: Test app
        run: dotnet test # Add specific test commands if needed

  deploy:
    runs-on: windows-latest

    needs: build # Ensure 'build' job completes before deployment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'

      - name: Publish app
        run: dotnet publish -c Release -o ./publish

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: published-app
          path: ./publish
